services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: surakshya
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project
    volumes:
      - ~/postgres-data:/var/lib/postgresql
    
  adminer:
    image: adminer
    ports:
      - "8080:8080"