export const sampleHtml = [
 `<h1>10 Tips for Healthy Living</h1><p>Living a healthy life doesn’t have to be complicated. Follow these simple tips to boost your well-being:</p><ul><li><strong>Eat balanced meals:</strong> Include fruits, vegetables, and proteins in every meal.</li><li><strong>Stay active:</strong> Aim for at least 30 minutes of exercise daily.</li><li><strong>Hydrate:</strong> Drink at least 8 glasses of water a day.</li></ul><blockquote>“The greatest wealth is health.” - Virgil</blockquote>`,
 `<h1>Exploring the Best Travel Destinations in 2024</h1><p>This year brings new opportunities for adventure. Here are some must-visit places:</p><ol><li><strong>Maldives:</strong> Pristine beaches and clear waters.</li><li><strong>Paris, France:</strong> The city of love and culture.</li><li><strong>Tokyo, Japan:</strong> A mix of tradition and modernity.</li></ol><p>Plan your trips early for the best deals!</p>`,
 `<h2>How to Start a Successful Blog</h2><p>Starting a blog can be rewarding. Follow these steps:</p><ul><li>Choose a niche you’re passionate about.</li><li>Set up a blogging platform like WordPress or Blogger.</li><li>Write high-quality, engaging content.</li></ul><blockquote>“Content is king, but engagement is queen, and the lady rules the house.”</blockquote><p>Don’t forget to promote your blog on social media!</p>`,
 `<h1>The Benefits of a Plant-Based Diet</h1><p>Switching to a plant-based diet has numerous benefits:</p><ul><li>Improves heart health.</li><li>Reduces the risk of chronic diseases.</li><li>Helps the environment by lowering your carbon footprint.</li></ul><table border='1'><thead><tr><th>Plant-Based Foods</th><th>Key Nutrients</th></tr></thead><tbody><tr><td>Legumes</td><td>Protein, Fiber</td></tr><tr><td>Leafy Greens</td><td>Vitamins A, C, and K</td></tr><tr><td>Fruits</td><td>Antioxidants, Natural Sugars</td></tr></tbody></table><p>Consider starting with one plant-based meal per day.</p>`,
 `<h1>Top 5 Productivity Hacks</h1><p>Boost your productivity with these simple strategies:</p><ol><li>Use the <em>Pomodoro Technique</em>: Work for 25 minutes, then take a 5-minute break.</li><li>Eliminate distractions by turning off notifications.</li><li>Plan your day with a to-do list or planner.</li><li>Prioritize tasks based on importance and deadlines.</li><li>Get enough sleep to stay focused.</li></ol><blockquote>“Productivity is never an accident. It is always the result of a commitment to excellence.”</blockquote>`,
 `<h1>Understanding Blockchain Technology</h1><p>Blockchain is revolutionizing the tech world. Here’s why it’s important:</p><ul><li>Decentralization: No central authority controls the data.</li><li>Transparency: Transactions are publicly recorded.</li><li>Security: Data is encrypted and tamper-proof.</li></ul><p>Here’s a simplified view:</p><table border='1'><thead><tr><th>Feature</th><th>Benefit</th></tr></thead><tbody><tr><td>Smart Contracts</td><td>Automate agreements</td></tr><tr><td>Cryptocurrency</td><td>Secure digital payments</td></tr></tbody></table>`,
 `<h2>5 Easy Home Workouts</h2><p>Stay fit without a gym membership by trying these home workouts:</p><ul><li><strong>Push-ups:</strong> Great for upper body strength.</li><li><strong>Squats:</strong> Builds lower body and core muscles.</li><li><strong>Plank:</strong> Enhances core stability.</li></ul><p>Consistency is key. Start small and build up over time!</p>`,
 `<h1>How to Save Money Effectively</h1><p>Saving money is a skill. Follow these tips:</p><ul><li>Track your expenses and create a budget.</li><li>Automate your savings to avoid spending temptations.</li><li>Cut down on unnecessary subscriptions and dining out.</li></ul><blockquote>“Do not save what is left after spending, but spend what is left after saving.”</blockquote>`,
 `<h2>The Future of AI</h2><p>Artificial Intelligence is shaping our world. Key trends include:</p><ol><li>Advancements in natural language processing.</li><li>Increased automation in industries.</li><li>Ethical considerations in AI development.</li></ol><p>Understanding these trends can help us adapt to a rapidly changing landscape.</p>`,
 `<h1>Essential Gardening Tips for Beginners</h1><p>Start your gardening journey with these simple tips:</p><ul><li>Choose the right plants for your climate.</li><li>Prepare soil with organic compost.</li><li>Water plants early in the morning or late evening.</li></ul><p>With a little care, you’ll have a thriving garden in no time!</p>`
  ]
  